# Generated by Django 6.0.3 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0004_result_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
